version: "3.8"
services:
  avows:
    build: "./"
    container_name: avows
    ports:
      - "8080:8080"
    volumes:
      - "/app/node_modules"
    networks:
      - mynetwork
    depends_on:
      - redis
  redis:
    container_name: redis
    image: "redis:latest"
    restart: always
    command: redis-server --save
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
